FROM golang:alpine AS builder

RUN mkdir /app
ADD . /app
WORKDIR /app

RUN go build -o server ./cmd

FROM alpine:latest
RUN apk add --no-cache bash

WORKDIR src

COPY --from=builder /app/server .
COPY --from=builder /app/assets/ ./assets/
COPY --from=builder /app/internal/services/template.html ./template/
COPY --from=builder /app/migrations .

ENTRYPOINT "./server"



