basePath: /
definitions:
  models.Account:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      tokens:
        additionalProperties:
          type: string
        type: object
      updatedAt:
        type: string
    type: object
  models.Company:
    properties:
      bank_detail:
        type: string
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      kind:
        type: string
      name:
        type: string
      phone:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8100
info:
  contact:
    email: support@ragger.com
    name: API Support
  description: This is a sample service ...
  license: {}
  termsOfService: http://swagger.io/terms/
  title: Ragger API
  version: "1.0"
paths:
  /api/company/register:
    post:
      description: Create a new company.
      parameters:
      - description: company
        in: body
        name: company
        required: true
        schema:
          $ref: '#/definitions/models.Company'
      produces:
      - application/json
      responses:
        "200":
          description: 'response structure: {message:"answer"}'
          schema:
            $ref: '#/definitions/models.Account'
        "400":
          description: 'response structure: {error:"error message"}'
          schema:
            type: string
        "500":
          description: 'response structure: {error:"error message"}'
          schema:
            type: string
      summary: Registration company of logistic-service service
      tags:
      - Company
  /health:
    get:
      description: Health check ragger service
      produces:
      - application/json
      responses:
        "200":
          description: 'response structure: {status:"UP"}'
          schema:
            type: string
      summary: Ragger health check
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
